site_name: YRLeet
theme:
  name: 'material'
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link 
    - content.code.annotation
    - content.code.copy
  language: 'zh'
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - schema: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/yongruifang
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/523415551

copyright: |
  &copy; 2024 <a href="https://github.com/yongruifang" target="_blank" rel="noopener">Yong Rui</a>

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
 - Home:
    - index.md
 - Leetcode:
    - 前言: leetcode/getting-started.md
    - 1.两数之和: leetcode/0001-twosum.md
  
